# Generated by Django 3.0.7 on 2020-06-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='complet',
            new_name='complete',
        ),
    ]
